/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-refresh/only-export-components */
/* eslint-disable @typescript-eslint/no-non-null-assertion */
import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from 'react';
import type { Language } from '@/types';
import { DEFAULT_LANGUAGE, LANGUAGE_STORAGE_KEY } from '@/utils/constants';

type TranslationKey = string;
// Each key maps to all 9 supported languages
type Translations = Record<TranslationKey, Partial<Record<Language, string>>>;

export const translations: Translations = {
  // ── Navigation ────────────────────────────────────────────────
  'nav.home': {
    en: 'Home',
    hi: 'होम',
    es: 'Inicio',
    fr: 'Accueil',
    de: 'Start',
    pt: 'Início',
    ar: 'الرئيسية',
    ja: 'ホーム',
    zh: '首页',
  },
  'nav.game': {
    en: 'Play',
    hi: 'खेलें',
    es: 'Jugar',
    fr: 'Jouer',
    de: 'Spielen',
    pt: 'Jogar',
    ar: 'العب',
    ja: 'プレイ',
    zh: '游戏',
  },
  'nav.leaderboard': {
    en: 'Leaderboard',
    hi: 'लीडरबोर्ड',
    es: 'Clasificación',
    fr: 'Classement',
    de: 'Rangliste',
    pt: 'Placar',
    ar: 'المتصدرون',
    ja: 'ランキング',
    zh: '排行榜',
  },
  'nav.language': {
    en: 'Language',
    hi: 'भाषा',
    es: 'Idioma',
    fr: 'Langue',
    de: 'Sprache',
    pt: 'Idioma',
    ar: 'اللغة',
    ja: '言語',
    zh: '语言',
  },

  // ── Hero / Home ───────────────────────────────────────────────
  'home.hero.title': {
    en: 'Make Every Choice Count',
    hi: 'हर निर्णय मायने रखता है',
    es: 'Haz que cada elección cuente',
    fr: 'Chaque choix compte',
    de: 'Jede Wahl zählt',
    pt: 'Faça cada escolha contar',
    ar: 'اجعل كل خيار مهماً',
    ja: 'すべての選択を大切に',
    zh: '让每个选择都有意义',
  },
  'home.hero.subtitle': {
    en: 'An AI-powered eco-awareness game that shows the real impact of your daily choices.',
    hi: 'एक AI-संचालित पर्यावरण जागरूकता खेल जो आपके दैनिक निर्णयों के असली प्रभाव को दिखाता है।',
    es: 'Un juego de conciencia ecológica impulsado por IA que muestra el impacto real de tus decisiones diarias.',
    fr: "Un jeu de sensibilisation écologique propulsé par IA qui montre l'impact réel de vos choix quotidiens.",
    de: 'Ein KI-gesteuertes Öko-Bewusstseinsspiel, das die echten Auswirkungen Ihrer täglichen Entscheidungen zeigt.',
    pt: 'Um jogo de consciência ecológica com IA que mostra o impacto real de suas escolhas diárias.',
    ar: 'لعبة وعي بيئي مدعومة بالذكاء الاصطناعي تُظهر التأثير الحقيقي لخياراتك اليومية.',
    ja: 'AIで毎日の選択が地球に与える本当の影響を示すエコ意識ゲーム。',
    zh: '一款AI驱动的生态意识游戏，展示您日常选择的真实影响。',
  },
  'home.cta.play': {
    en: 'Start EcoQuest',
    hi: 'EcoQuest शुरू करें',
    es: 'Iniciar EcoQuest',
    fr: 'Démarrer EcoQuest',
    de: 'EcoQuest starten',
    pt: 'Iniciar EcoQuest',
    ar: 'ابدأ EcoQuest',
    ja: 'EcoQuestを始める',
    zh: '开始EcoQuest',
  },
  'home.cta.leaderboard': {
    en: 'View Leaderboard',
    hi: 'लीडरबोर्ड देखें',
    es: 'Ver clasificación',
    fr: 'Voir le classement',
    de: 'Rangliste ansehen',
    pt: 'Ver placar',
    ar: 'عرض المتصدرين',
    ja: 'ランキングを見る',
    zh: '查看排行榜',
  },
  'home.stats.warriors': {
    en: 'Eco Warriors',
    hi: 'इको योद्धा',
    es: 'Guerreros Eco',
    fr: 'Guerriers Éco',
    de: 'Öko-Krieger',
    pt: 'Guerreiros Eco',
    ar: 'المحاربون البيئيون',
    ja: 'エコ戦士',
    zh: '生态勇士',
  },
  'home.stats.saved': {
    en: 't CO₂ Saved',
    hi: 't CO₂ बचाई',
    es: 't CO₂ ahorrado',
    fr: 't CO₂ économisé',
    de: 't CO₂ eingespart',
    pt: 't CO₂ poupado',
    ar: 'طن CO₂ محفوظ',
    ja: 't CO₂削減',
    zh: '吨CO₂节省',
  },
  'home.stats.quests': {
    en: 'Quests Completed',
    hi: 'क्वेस्ट पूर्ण',
    es: 'Quests completados',
    fr: 'Quêtes complétées',
    de: 'Quests abgeschlossen',
    pt: 'Missões concluídas',
    ar: 'مهام مكتملة',
    ja: 'クエスト完了',
    zh: '任务完成',
  },

  // ── Game ──────────────────────────────────────────────────────
  'game.start': {
    en: 'Begin Adventure',
    hi: 'साहसिक यात्रा शुरू करें',
    es: 'Comenzar aventura',
    fr: "Commencer l'aventure",
    de: 'Abenteuer beginnen',
    pt: 'Começar aventura',
    ar: 'ابدأ المغامرة',
    ja: '冒険を始める',
    zh: '开始冒险',
  },
  'game.choose_char': {
    en: 'Choose Your Character',
    hi: 'अपना किरदार चुनें',
    es: 'Elige tu personaje',
    fr: 'Choisissez votre personnage',
    de: 'Charakter wählen',
    pt: 'Escolha seu personagem',
    ar: 'اختر شخصيتك',
    ja: 'キャラクターを選んで',
    zh: '选择您的角色',
  },
  'game.eco_points': {
    en: 'Eco-Points',
    hi: 'इको-पॉइंट',
    es: 'Eco-Puntos',
    fr: 'Éco-Points',
    de: 'Öko-Punkte',
    pt: 'Eco-Pontos',
    ar: 'نقاط بيئية',
    ja: 'エコポイント',
    zh: '生态分',
  },
  'game.scenario': {
    en: 'Scenario',
    hi: 'परिदृश्य',
    es: 'Escenario',
    fr: 'Scénario',
    de: 'Szenario',
    pt: 'Cenário',
    ar: 'سيناريو',
    ja: 'シナリオ',
    zh: '场景',
  },
  'game.choose': {
    en: 'Make your choice',
    hi: 'अपना निर्णय चुनें',
    es: 'Elige tu acción',
    fr: 'Faites votre choix',
    de: 'Treffe deine Wahl',
    pt: 'Faça sua escolha',
    ar: 'اختر خيارك',
    ja: '選択してください',
    zh: '做出您的选择',
  },
  'game.next': {
    en: 'Next',
    hi: 'अगला',
    es: 'Siguiente',
    fr: 'Suivant',
    de: 'Weiter',
    pt: 'Próximo',
    ar: 'التالي',
    ja: '次へ',
    zh: '下一步',
  },
  'game.complete': {
    en: 'See Results',
    hi: 'परिणाम देखें',
    es: 'Ver resultados',
    fr: 'Voir les résultats',
    de: 'Ergebnisse sehen',
    pt: 'Ver resultados',
    ar: 'اعرض النتائج',
    ja: '結果を見る',
    zh: '查看结果',
  },
  'game.tip': {
    en: 'Eco-friendly choices reduce your carbon footprint and earn more points!',
    hi: 'पर्यावरण-अनुकूल विकल्प आपके कार्बन फुटप्रिंट को कम करते हैं!',
    es: '¡Las elecciones ecológicas reducen tu huella de carbono!',
    fr: 'Les choix écologiques réduisent votre empreinte carbone!',
    de: 'Ökologische Entscheidungen reduzieren Ihren CO₂-Fußabdruck!',
    pt: 'Escolhas ecológicas reduzem sua pegada de carbono!',
    ar: 'الخيارات الصديقة للبيئة تقلل بصمتك الكربونية!',
    ja: '環境に優しい選択で炭素排出量を減らせます！',
    zh: '环保选择减少您的碳足迹！',
  },

  // ── Characters ────────────────────────────────────────────────
  'char.alex.name': {
    en: 'Alex',
    hi: 'एलेक्स',
    es: 'Alex',
    fr: 'Alex',
    de: 'Alex',
    pt: 'Alex',
    ar: 'أليكس',
    ja: 'アレックス',
    zh: '亚历克斯',
  },
  'char.alex.desc': {
    en: 'Tech-savvy urban explorer',
    hi: 'तकनीक-प्रेमी शहरी खोजकर्ता',
    es: 'Explorador urbano tech',
    fr: 'Explorateur urbain tech',
    de: 'Tech-affiner Stadtentdecker',
    pt: 'Explorador urbano tech',
    ar: 'مستكشف حضري ذكي',
    ja: 'テクノロジーに詳しい都市探検家',
    zh: '精通科技的城市探险家',
  },
  'char.maya.name': {
    en: 'Maya',
    hi: 'माया',
    es: 'Maya',
    fr: 'Maya',
    de: 'Maya',
    pt: 'Maya',
    ar: 'مايا',
    ja: 'マヤ',
    zh: '玛雅',
  },
  'char.maya.desc': {
    en: 'Nature-loving sustainability advocate',
    hi: 'प्रकृति-प्रेमी स्थिरता समर्थक',
    es: 'Defensora de la sostenibilidad',
    fr: "Défenseure de l'environnement",
    de: 'Nachhaltigkeits-Verfechterin',
    pt: 'Defensora da sustentabilidade',
    ar: 'مدافعة عن الاستدامة',
    ja: '自然愛好家のサステナビリティ推進者',
    zh: '热爱自然的可持续发展倡导者',
  },
  'char.riya.name': {
    en: 'Riya',
    hi: 'रिया',
    es: 'Riya',
    fr: 'Riya',
    de: 'Riya',
    pt: 'Riya',
    ar: 'ريا',
    ja: 'リヤ',
    zh: '丽雅',
  },
  'char.riya.desc': {
    en: 'Mindful student making green choices',
    hi: 'सचेत छात्रा जो हरे विकल्प चुनती है',
    es: 'Estudiante consciente y ecológica',
    fr: 'Étudiante consciente et écologique',
    de: 'Aufmerksame Studentin mit grünen Entscheidungen',
    pt: 'Estudante consciente e ecológica',
    ar: 'طالبة واعية تختار الخيارات الخضراء',
    ja: '環境に配慮した選択をする意識高い学生',
    zh: '做出绿色选择的有意识学生',
  },
  'char.carlos.name': {
    en: 'Carlos',
    hi: 'कार्लोस',
    es: 'Carlos',
    fr: 'Carlos',
    de: 'Carlos',
    pt: 'Carlos',
    ar: 'كارلوس',
    ja: 'カルロス',
    zh: '卡洛斯',
  },
  'char.carlos.desc': {
    en: 'Community builder & green entrepreneur',
    hi: 'समुदाय निर्माता और हरे उद्यमी',
    es: 'Emprendedor verde comunitario',
    fr: 'Entrepreneur vert et bâtisseur de communauté',
    de: 'Grüner Unternehmer und Gemeinschaftsgestalter',
    pt: 'Empreendedor verde e construtor comunitário',
    ar: 'رائد أعمال أخضر وبناء مجتمعي',
    ja: 'コミュニティビルダー・グリーン起業家',
    zh: '社区建设者和绿色企业家',
  },

  // ── Scenario Titles/Descriptions ─────────────────────────────
  'scenario.commute.title': {
    en: 'Morning Commute',
    hi: 'सुबह की यात्रा',
    es: 'Viaje matutino',
    fr: 'Trajet du matin',
    de: 'Morgenpendelfahrt',
    pt: 'Deslocamento matinal',
    ar: 'التنقل الصباحي',
    ja: '朝の通勤',
    zh: '早晨通勤',
  },
  'scenario.commute.desc': {
    en: 'How will you get to the office today?',
    hi: 'आज आप ऑफिस कैसे जाएंगे?',
    es: '¿Cómo irás a la oficina hoy?',
    fr: "Comment allez-vous au bureau aujourd'hui?",
    de: 'Wie kommen Sie heute ins Büro?',
    pt: 'Como você vai ao escritório hoje?',
    ar: 'كيف ستذهب إلى المكتب اليوم؟',
    ja: '今日どうやって会社に行きますか？',
    zh: '今天你怎么去办公室？',
  },
  'scenario.diet.title': {
    en: 'Lunch Break',
    hi: 'दोपहर का खाना',
    es: 'Pausa del almuerzo',
    fr: 'Pause déjeuner',
    de: 'Mittagspause',
    pt: 'Pausa para almoço',
    ar: 'استراحة الغداء',
    ja: '昼休み',
    zh: '午休',
  },
  'scenario.diet.desc': {
    en: "What's on your plate today?",
    hi: 'आज आपकी थाली में क्या है?',
    es: '¿Qué hay en tu plato hoy?',
    fr: "Qu'est-ce qu'il y a dans votre assiette?",
    de: 'Was ist heute auf Ihrem Teller?',
    pt: 'O que está no seu prato hoje?',
    ar: 'ماذا في طبقك اليوم؟',
    ja: '今日のお昼ご飯は何ですか？',
    zh: '今天你的盘子里有什么？',
  },
  'scenario.energy.title': {
    en: 'Evening at Home',
    hi: 'घर पर शाम',
    es: 'Tarde en casa',
    fr: 'Soirée à la maison',
    de: 'Abend zu Hause',
    pt: 'Noite em casa',
    ar: 'مساء في المنزل',
    ja: '家での夜',
    zh: '家中傍晚',
  },
  'scenario.energy.desc': {
    en: 'How will you power your evening?',
    hi: 'अपनी शाम को ऊर्जा कैसे देंगे?',
    es: '¿Cómo energizarás tu tarde?',
    fr: 'Comment alimenterez-vous votre soirée?',
    de: 'Wie werden Sie Ihren Abend versorgen?',
    pt: 'Como você vai alimentar sua noite?',
    ar: 'كيف ستشغل مساءك؟',
    ja: '今夜のエネルギーはどうしますか？',
    zh: '你怎么为今晚供电？',
  },
  'scenario.shopping.title': {
    en: 'Weekend Shopping',
    hi: 'सप्ताहांत खरीदारी',
    es: 'Compras de fin de semana',
    fr: 'Courses du week-end',
    de: 'Wochenendeinkauf',
    pt: 'Compras de fim de semana',
    ar: 'تسوق نهاية الأسبوع',
    ja: '週末のショッピング',
    zh: '周末购物',
  },
  'scenario.shopping.desc': {
    en: 'Time to stock up — what do you need and how do you get it?',
    hi: 'स्टॉक करने का समय — आपको क्या चाहिए और कैसे मिलेगा?',
    es: 'Hora de abastecerse — ¿qué necesitas y cómo lo consigues?',
    fr: 'Il est temps de faire les courses — comment le faites-vous?',
    de: 'Zeit zum Einkaufen — wie machen Sie es?',
    pt: 'Hora de estocar — o que você precisa e como consegue?',
    ar: 'وقت التسوق — ماذا تحتاج وكيف تحصل عليه؟',
    ja: '買い物の時間です — どうやって買いますか？',
    zh: '购物时间 — 你需要什么，怎么获取？',
  },
  'scenario.heating.title': {
    en: 'Cold Winter Night',
    hi: 'ठंडी सर्दियों की रात',
    es: 'Noche fría de invierno',
    fr: "Nuit froide d'hiver",
    de: 'Kalte Winternacht',
    pt: 'Noite fria de inverno',
    ar: 'ليلة شتاء باردة',
    ja: '寒い冬の夜',
    zh: '寒冷的冬夜',
  },
  'scenario.heating.desc': {
    en: 'The temperature drops — how do you stay warm?',
    hi: 'तापमान गिर रहा है — आप गर्म कैसे रहेंगे?',
    es: 'La temperatura baja — ¿cómo te mantienes abrigado?',
    fr: 'La température chute — comment restez-vous au chaud?',
    de: 'Die Temperatur fällt — wie bleiben Sie warm?',
    pt: 'A temperatura cai — como você fica aquecido?',
    ar: 'تنخفض درجة الحرارة — كيف تبقى دافئاً؟',
    ja: '気温が下がる — どうやって暖まりますか？',
    zh: '气温下降 — 你怎么保暖？',
  },
  'scenario.water.title': {
    en: 'Water at Home',
    hi: 'घर पर पानी',
    es: 'Agua en casa',
    fr: "L'eau à la maison",
    de: 'Wasser zu Hause',
    pt: 'Água em casa',
    ar: 'الماء في المنزل',
    ja: '家での水',
    zh: '家中用水',
  },
  'scenario.water.desc': {
    en: 'How will you manage your daily water usage?',
    hi: 'आप अपने दैनिक पानी के उपयोग को कैसे प्रबंधित करेंगे?',
    es: '¿Cómo gestionarás tu uso diario de agua?',
    fr: 'Comment allez-vous gérer votre consommation quotidienne?',
    de: 'Wie werden Sie Ihren täglichen Wasserverbrauch verwalten?',
    pt: 'Como você vai gerenciar seu uso de água?',
    ar: 'كيف ستدير استهلاكك اليومي للمياه؟',
    ja: '毎日の水の使い方はどうしますか？',
    zh: '你如何管理日常用水？',
  },
  'scenario.travel.title': {
    en: 'Holiday Plans',
    hi: 'छुट्टी की योजना',
    es: 'Planes de vacaciones',
    fr: 'Plans de vacances',
    de: 'Urlaubspläne',
    pt: 'Planos de férias',
    ar: 'خطط العطلة',
    ja: '休暇の計画',
    zh: '假期计划',
  },
  'scenario.travel.desc': {
    en: 'Time off! How will you spend it?',
    hi: 'छुट्टी का समय! आप इसे कैसे बिताएंगे?',
    es: '¡Tiempo libre! ¿Cómo lo pasarás?',
    fr: 'Des vacances! Comment allez-vous les passer?',
    de: 'Urlaub! Wie werden Sie ihn verbringen?',
    pt: 'Férias! Como você as passará?',
    ar: 'إجازة! كيف ستقضيها؟',
    ja: '休暇です！どう過ごしますか？',
    zh: '假期到了！你怎么度过？',
  },
  'scenario.waste.title': {
    en: 'Waste Management',
    hi: 'कचरा प्रबंधन',
    es: 'Gestión de residuos',
    fr: 'Gestion des déchets',
    de: 'Abfallmanagement',
    pt: 'Gestão de resíduos',
    ar: 'إدارة النفايات',
    ja: '廃棄物管理',
    zh: '垃圾管理',
  },
  'scenario.waste.desc': {
    en: "What do you do with today's waste?",
    hi: 'आज के कचरे का क्या करेंगे?',
    es: '¿Qué haces con los residuos de hoy?',
    fr: "Que faites-vous avec les déchets d'aujourd'hui?",
    de: 'Was tun Sie mit dem heutigen Abfall?',
    pt: 'O que você faz com o lixo de hoje?',
    ar: 'ماذا تفعل بنفايات اليوم؟',
    ja: '今日のごみをどうしますか？',
    zh: '今天的废物你怎么处理？',
  },
  'scenario.digital.title': {
    en: 'Digital Life',
    hi: 'डिजिटल जीवन',
    es: 'Vida digital',
    fr: 'Vie numérique',
    de: 'Digitales Leben',
    pt: 'Vida digital',
    ar: 'الحياة الرقمية',
    ja: 'デジタルライフ',
    zh: '数字生活',
  },
  'scenario.digital.desc': {
    en: 'How do you use your devices and internet today?',
    hi: 'आज आप अपने डिवाइस और इंटरनेट का उपयोग कैसे करेंगे?',
    es: '¿Cómo usas tus dispositivos e internet hoy?',
    fr: 'Comment utilisez-vous vos appareils et internet?',
    de: 'Wie nutzen Sie Ihre Geräte und das Internet?',
    pt: 'Como você usa seus dispositivos e internet?',
    ar: 'كيف تستخدم أجهزتك والإنترنت اليوم؟',
    ja: '今日のデバイスとインターネットの使い方は？',
    zh: '你今天如何使用设备和互联网？',
  },

  // ── Choices — Commute ─────────────────────────────────────────
  'choice.cycle': {
    en: '🚲 Cycle',
    hi: '🚲 साइकिल',
    es: '🚲 Bicicleta',
    fr: '🚲 Vélo',
    de: '🚲 Fahrrad',
    pt: '🚲 Bicicleta',
    ar: '🚲 دراجة',
    ja: '🚲 自転車',
    zh: '🚲 骑车',
  },
  'choice.cycle.desc': {
    en: 'Zero emissions, great exercise!',
    hi: 'शून्य उत्सर्जन, अच्छा व्यायाम!',
    es: '¡Cero emisiones!',
    fr: 'Zéro émission, excellent exercice!',
    de: 'Null Emissionen, tolle Übung!',
    pt: 'Zero emissões, ótimo exercício!',
    ar: 'صفر انبعاثات!',
    ja: '排出ゼロ！素晴らしい運動！',
    zh: '零排放，极好的锻炼！',
  },
  'choice.walk': {
    en: '🚶 Walk',
    hi: '🚶 पैदल चलें',
    es: '🚶 Caminar',
    fr: '🚶 Marcher',
    de: '🚶 Laufen',
    pt: '🚶 Caminhar',
    ar: '🚶 المشي',
    ja: '🚶 歩く',
    zh: '🚶 步行',
  },
  'choice.walk.desc': {
    en: 'Healthy and eco-friendly',
    hi: 'स्वस्थ और पर्यावरण-अनुकूल',
    es: 'Sano y ecológico',
    fr: 'Sain et écologique',
    de: 'Gesund und umweltfreundlich',
    pt: 'Saudável e ecológico',
    ar: 'صحي وصديق للبيئة',
    ja: '健康的で環境に優しい',
    zh: '健康又环保',
  },
  'choice.metro': {
    en: '🚇 Metro/Bus',
    hi: '🚇 मेट्रो/बस',
    es: '🚇 Metro/Bus',
    fr: '🚇 Métro/Bus',
    de: '🚇 U-Bahn/Bus',
    pt: '🚇 Metrô/Ônibus',
    ar: '🚇 مترو/حافلة',
    ja: '🚇 地下鉄/バス',
    zh: '🚇 地铁/公交',
  },
  'choice.metro.desc': {
    en: 'Shared transport cuts emissions',
    hi: 'साझा परिवहन उत्सर्जन कम करता है',
    es: 'Transporte compartido',
    fr: 'Transport partagé réduit les émissions',
    de: 'Gemeinschaftsverkehr reduziert Emissionen',
    pt: 'Transporte compartilhado',
    ar: 'النقل المشترك يقلل الانبعاثات',
    ja: '共有交通で排出削減',
    zh: '共享交通减少排放',
  },
  'choice.car': {
    en: '🚗 Private Car',
    hi: '🚗 निजी कार',
    es: '🚗 Auto particular',
    fr: '🚗 Voiture privée',
    de: '🚗 Privatauto',
    pt: '🚗 Carro particular',
    ar: '🚗 سيارة خاصة',
    ja: '🚗 自家用車',
    zh: '🚗 私家车',
  },
  'choice.car.desc': {
    en: 'High emissions, stuck in traffic',
    hi: 'उच्च उत्सर्जन',
    es: 'Altas emisiones',
    fr: 'Émissions élevées, dans les embouteillages',
    de: 'Hohe Emissionen, Stau',
    pt: 'Altas emissões, trânsito',
    ar: 'انبعاثات عالية',
    ja: '高排出、渋滞',
    zh: '高排放，堵车',
  },

  // ── Choices — Diet ────────────────────────────────────────────
  'choice.plant': {
    en: '🥗 Plant-based',
    hi: '🥗 शाकाहारी',
    es: '🥗 Vegetal',
    fr: '🥗 Végétalien',
    de: '🥗 Pflanzlich',
    pt: '🥗 Vegetal',
    ar: '🥗 نباتي',
    ja: '🥗 植物性',
    zh: '🥗 植物性',
  },
  'choice.plant.desc': {
    en: 'Lowest carbon footprint',
    hi: 'सबसे कम कार्बन',
    es: 'Menor huella de carbono',
    fr: 'Empreinte carbone minimale',
    de: 'Geringster CO₂-Fußabdruck',
    pt: 'Menor pegada de carbono',
    ar: 'أقل بصمة كربونية',
    ja: '最小の炭素フットプリント',
    zh: '最小碳足迹',
  },
  'choice.veggie': {
    en: '🧀 Vegetarian',
    hi: '🧀 वेजिटेरियन',
    es: '🧀 Vegetariano',
    fr: '🧀 Végétarien',
    de: '🧀 Vegetarisch',
    pt: '🧀 Vegetariano',
    ar: '🧀 نباتي لبني',
    ja: '🧀 ベジタリアン',
    zh: '🧀 素食',
  },
  'choice.veggie.desc': {
    en: 'Low-carbon dairy diet',
    hi: 'कम-कार्बन डेयरी',
    es: 'Dieta láctea baja en carbono',
    fr: 'Régime lacté faible en carbone',
    de: 'Kohlenstoffarme Milchdiät',
    pt: 'Dieta láctea de baixo carbono',
    ar: 'نظام غذائي منخفض الكربون',
    ja: '低炭素乳製品食',
    zh: '低碳乳制品饮食',
  },
  'choice.meat': {
    en: '🍗 Meat Meal',
    hi: '🍗 मांसाहारी',
    es: '🍗 Comida con carne',
    fr: '🍗 Repas carné',
    de: '🍗 Fleischmahlzeit',
    pt: '🍗 Refeição com carne',
    ar: '🍗 وجبة لحوم',
    ja: '🍗 肉料理',
    zh: '🍗 肉类餐',
  },
  'choice.meat.desc': {
    en: 'High land & water use',
    hi: 'अधिक भूमि और जल',
    es: 'Alto uso de tierra y agua',
    fr: 'Utilisation élevée des terres',
    de: 'Hoher Land- und Wasserverbrauch',
    pt: 'Alto uso de terra e água',
    ar: 'استخدام مرتفع للأراضي',
    ja: '土地と水の大量使用',
    zh: '高土地和水资源使用',
  },

  // ── Choices — Energy ─────────────────────────────────────────
  'choice.solar': {
    en: '☀️ Solar/Renewables',
    hi: '☀️ सौर/नवीकरणीय',
    es: '☀️ Solar/Renovables',
    fr: '☀️ Solaire/Renouvelable',
    de: '☀️ Solar/Erneuerbar',
    pt: '☀️ Solar/Renovável',
    ar: '☀️ طاقة شمسية',
    ja: '☀️ 太陽光/再生可能',
    zh: '☀️ 太阳能/可再生',
  },
  'choice.solar.desc': {
    en: 'Clean energy at home',
    hi: 'घर पर स्वच्छ ऊर्जा',
    es: 'Energía limpia en casa',
    fr: 'Énergie propre à la maison',
    de: 'Saubere Energie zu Hause',
    pt: 'Energia limpa em casa',
    ar: 'طاقة نظيفة في المنزل',
    ja: '家での清潔エネルギー',
    zh: '家中清洁能源',
  },
  'choice.efficient': {
    en: '💡 Energy-efficient',
    hi: '💡 ऊर्जा-कुशल',
    es: '💡 Eficiencia energética',
    fr: '💡 Économe en énergie',
    de: '💡 Energieeffizient',
    pt: '💡 Eficiente em energia',
    ar: '💡 موفر للطاقة',
    ja: '💡 エネルギー効率',
    zh: '💡 节能',
  },
  'choice.efficient.desc': {
    en: 'LED lights & smart usage',
    hi: 'LED और स्मार्ट उपयोग',
    es: 'LEDs y uso inteligente',
    fr: 'Ampoules LED et utilisation intelligente',
    de: 'LED und intelligente Nutzung',
    pt: 'LEDs e uso inteligente',
    ar: 'إضاءة LED واستخدام ذكي',
    ja: 'LEDと賢い使用',
    zh: 'LED灯和智能使用',
  },
  'choice.standard': {
    en: '🔌 Standard usage',
    hi: '🔌 सामान्य उपयोग',
    es: '🔌 Uso estándar',
    fr: '🔌 Consommation standard',
    de: '🔌 Standardverbrauch',
    pt: '🔌 Uso padrão',
    ar: '🔌 الاستخدام القياسي',
    ja: '🔌 標準使用',
    zh: '🔌 标准使用',
  },
  'choice.standard.desc': {
    en: 'Average household energy use',
    hi: 'औसत घरेलू ऊर्जा उपयोग',
    es: 'Uso doméstico promedio',
    fr: 'Consommation ménagère moyenne',
    de: 'Durchschnittlicher Haushaltsverbrauch',
    pt: 'Uso doméstico médio',
    ar: 'استهلاك المنزل المتوسط',
    ja: '平均的な家庭エネルギー使用',
    zh: '平均家庭能源使用',
  },

  // ── Choices — Shopping ────────────────────────────────────────
  'choice.local': {
    en: '🛒 Local Market',
    hi: '🛒 स्थानीय बाज़ार',
    es: '🛒 Mercado local',
    fr: '🛒 Marché local',
    de: '🛒 Lokaler Markt',
    pt: '🛒 Mercado local',
    ar: '🛒 السوق المحلي',
    ja: '🛒 地元市場',
    zh: '🛒 本地市场',
  },
  'choice.local.desc': {
    en: 'Support local, cut food miles',
    hi: 'स्थानीय समर्थन, खाद्य मील कम',
    es: 'Apoyo local, menos kilómetros',
    fr: 'Soutien local, moins de km',
    de: 'Lokal unterstützen, Transportwege kürzen',
    pt: 'Apoio local, reduz transporte',
    ar: 'دعم محلي وتقليل المسافات',
    ja: '地元支援で輸送距離削減',
    zh: '支持本地，减少运输里程',
  },
  'choice.secondhand': {
    en: '♻️ Second-hand',
    hi: '♻️ सेकेंड-हैंड',
    es: '♻️ De segunda mano',
    fr: '♻️ Occasion',
    de: '♻️ Second-Hand',
    pt: '♻️ Segunda mão',
    ar: '♻️ مستعمل',
    ja: '♻️ 中古品',
    zh: '♻️ 二手货',
  },
  'choice.secondhand.desc': {
    en: 'Circular economy — extend product life',
    hi: 'सर्कुलर अर्थव्यवस्था',
    es: 'Economía circular',
    fr: 'Économie circulaire',
    de: 'Kreislaufwirtschaft',
    pt: 'Economia circular',
    ar: 'اقتصاد دائري',
    ja: '循環経済で製品延命',
    zh: '循环经济 — 延长产品寿命',
  },
  'choice.online': {
    en: '📦 Online Delivery',
    hi: '📦 ऑनलाइन डिलीवरी',
    es: '📦 Entrega online',
    fr: '📦 Livraison en ligne',
    de: '📦 Online-Lieferung',
    pt: '📦 Entrega online',
    ar: '📦 التوصيل الإلكتروني',
    ja: '📦 オンライン配送',
    zh: '📦 网购配送',
  },
  'choice.online.desc': {
    en: 'Consolidated delivery, medium impact',
    hi: 'समेकित डिलीवरी',
    es: 'Entrega consolidada',
    fr: 'Livraison consolidée',
    de: 'Konsolidierte Lieferung',
    pt: 'Entrega consolidada',
    ar: 'توصيل موحد',
    ja: '一括配送、中程度の影響',
    zh: '合并配送，中等影响',
  },
  'choice.mall': {
    en: '🏬 Drive to Mall',
    hi: '🏬 मॉल जाएं',
    es: '🏬 Ir al centro',
    fr: '🏬 Centre commercial',
    de: '🏬 Einkaufszentrum',
    pt: '🏬 Shopping center',
    ar: '🏬 التسوق بالسيارة',
    ja: '🏬 車でモールへ',
    zh: '🏬 开车去商场',
  },
  'choice.mall.desc': {
    en: 'High car emissions + overbuying risk',
    hi: 'उच्च कार उत्सर्जन',
    es: 'Altas emisiones de coche',
    fr: 'Émissions élevées voiture',
    de: 'Hohe Auto-Emissionen',
    pt: 'Altas emissões de carro',
    ar: 'انبعاثات سيارة عالية',
    ja: '高い車排出量',
    zh: '高汽车排放+过度消费风险',
  },

  // ── Choices — Heating ─────────────────────────────────────────
  'choice.heatpump': {
    en: '🌡️ Heat Pump',
    hi: '🌡️ हीट पंप',
    es: '🌡️ Bomba de calor',
    fr: '🌡️ Pompe à chaleur',
    de: '🌡️ Wärmepumpe',
    pt: '🌡️ Bomba de calor',
    ar: '🌡️ مضخة حرارية',
    ja: '🌡️ ヒートポンプ',
    zh: '🌡️ 热泵',
  },
  'choice.heatpump.desc': {
    en: '3x more efficient than gas heating',
    hi: 'गैस हीटिंग से 3x अधिक कुशल',
    es: '3 veces más eficiente',
    fr: '3x plus efficace que le gaz',
    de: '3x effizienter als Gasheizung',
    pt: '3x mais eficiente que gás',
    ar: 'أكفأ 3 مرات من التدفئة بالغاز',
    ja: 'ガス暖房の3倍効率的',
    zh: '比燃气供暖效率高3倍',
  },
  'choice.sweater': {
    en: '🧥 Layer Up',
    hi: '🧥 गर्म कपड़े',
    es: '🧥 Abrigarse',
    fr: '🧥 Porter des couches',
    de: '🧥 Mehrere Schichten',
    pt: '🧥 Agasalhar-se',
    ar: '🧥 ارتداء الملابس الدافئة',
    ja: '🧥 重ね着',
    zh: '🧥 多穿衣服',
  },
  'choice.sweater.desc': {
    en: 'Wear a sweater instead of turning up heat',
    hi: 'हीटिंग बढ़ाने की जगह स्वेटर पहनें',
    es: 'Ponte un jersey en vez de calefacción',
    fr: 'Portez un pull plutôt que chauffer plus',
    de: 'Pullover statt Heizung aufdrehen',
    pt: 'Vista um suéter em vez de aquecer mais',
    ar: 'ارتد كنزة بدل رفع التدفئة',
    ja: '暖房を上げる代わりにセーターを着る',
    zh: '穿毛衣而不是调高暖气',
  },
  'choice.gas': {
    en: '🔥 Gas Heating',
    hi: '🔥 गैस हीटिंग',
    es: '🔥 Calefacción de gas',
    fr: '🔥 Chauffage au gaz',
    de: '🔥 Gasheizung',
    pt: '🔥 Aquecimento a gás',
    ar: '🔥 تدفئة الغاز',
    ja: '🔥 ガス暖房',
    zh: '🔥 燃气供暖',
  },
  'choice.gas.desc': {
    en: 'Fossil fuel, high CO₂',
    hi: 'जीवाश्म ईंधन, उच्च CO₂',
    es: 'Combustible fósil, alto CO₂',
    fr: 'Combustible fossile, CO₂ élevé',
    de: 'Fossiler Brennstoff, hohe CO₂',
    pt: 'Combustível fóssil, alto CO₂',
    ar: 'وقود أحفوري عالي CO₂',
    ja: '化石燃料、高CO₂',
    zh: '化石燃料，高CO₂',
  },

  // ── Choices — Water ───────────────────────────────────────────
  'choice.shower': {
    en: '🚿 Short Shower',
    hi: '🚿 छोटा स्नान',
    es: '🚿 Ducha corta',
    fr: '🚿 Douche courte',
    de: '🚿 Kurzdusche',
    pt: '🚿 Ducha curta',
    ar: '🚿 استحمام قصير',
    ja: '🚿 短いシャワー',
    zh: '🚿 短时淋浴',
  },
  'choice.shower.desc': {
    en: '4-min shower saves 40L water',
    hi: '4 मिनट का शॉवर 40L पानी बचाता है',
    es: 'Ducha de 4 min ahorra 40L',
    fr: '4 min douche économise 40L',
    de: '4-Min Dusche spart 40L',
    pt: 'Ducha de 4 min poupa 40L',
    ar: '4 دقائق توفر 40 لتر',
    ja: '4分シャワーで40L節水',
    zh: '4分钟淋浴节省40升水',
  },
  'choice.rainwater': {
    en: '💧 Rainwater Harvest',
    hi: '💧 वर्षा जल संचयन',
    es: '💧 Agua de lluvia',
    fr: '💧 Collecte pluie',
    de: '💧 Regenwasser',
    pt: '💧 Coleta de chuva',
    ar: '💧 تجميع مياه الأمطار',
    ja: '💧 雨水収集',
    zh: '💧 雨水收集',
  },
  'choice.rainwater.desc': {
    en: 'Capture rain for gardening & cleaning',
    hi: 'बागवानी और सफाई के लिए वर्षा एकत्र करें',
    es: 'Capture lluvia para jardinería',
    fr: 'Recueillez la pluie pour jardinage',
    de: 'Regenwasser für Garten sammeln',
    pt: 'Capturar chuva para jardim',
    ar: 'تجميع الأمطار للحديقة',
    ja: '雨水を庭と清掃に活用',
    zh: '收集雨水用于园艺和清洁',
  },
  'choice.bath': {
    en: '🛁 Full Bath',
    hi: '🛁 पूर्ण स्नान',
    es: '🛁 Baño completo',
    fr: '🛁 Bain complet',
    de: '🛁 Vollbad',
    pt: '🛁 Banho completo',
    ar: '🛁 حمام كامل',
    ja: '🛁 全身浴',
    zh: '🛁 全身浴',
  },
  'choice.bath.desc': {
    en: 'Uses 150L of hot water',
    hi: '150L गर्म पानी का उपयोग',
    es: 'Usa 150L de agua caliente',
    fr: 'Utilise 150L eau chaude',
    de: 'Verbraucht 150L heißes Wasser',
    pt: 'Usa 150L de água quente',
    ar: 'يستهلك 150 لتر ماء ساخن',
    ja: '150Lの湯を使用',
    zh: '使用150升热水',
  },

  // ── Choices — Travel ──────────────────────────────────────────
  'choice.train': {
    en: '🚂 Train Journey',
    hi: '🚂 ट्रेन यात्रा',
    es: '🚂 Viaje en tren',
    fr: '🚂 Voyage en train',
    de: '🚂 Zugreise',
    pt: '🚂 Viagem de trem',
    ar: '🚂 سفر بالقطار',
    ja: '🚂 列車旅行',
    zh: '🚂 火车旅行',
  },
  'choice.train.desc': {
    en: '90% less CO₂ than flying',
    hi: 'उड़ान से 90% कम CO₂',
    es: '90% menos CO₂ que volar',
    fr: "90% moins de CO₂ que l'avion",
    de: '90% weniger CO₂ als Fliegen',
    pt: '90% menos CO₂ que voar',
    ar: 'أقل CO₂ بنسبة 90% من الطيران',
    ja: '飛行機より90%少ないCO₂',
    zh: '比飞行少90%的CO₂',
  },
  'choice.staycation': {
    en: '🏕️ Staycation',
    hi: '🏕️ स्थानीय छुट्टी',
    es: '🏕️ Vacaciones locales',
    fr: '🏕️ Rester ici',
    de: '🏕️ Urlaub daheim',
    pt: '🏕️ Férias locais',
    ar: '🏕️ إجازة محلية',
    ja: '🏕️ ステイケーション',
    zh: '🏕️ 本地度假',
  },
  'choice.staycation.desc': {
    en: 'Zero transport emissions, discover locally',
    hi: 'शून्य परिवहन उत्सर्जन',
    es: 'Cero emisiones de transporte',
    fr: 'Zéro émission de transport',
    de: 'Null Transportemissionen',
    pt: 'Zero emissões de transporte',
    ar: 'صفر انبعاثات نقل',
    ja: '輸送排出ゼロ、地元発見',
    zh: '零交通排放，发现本地',
  },
  'choice.flight': {
    en: '✈️ Long-haul Flight',
    hi: '✈️ लंबी उड़ान',
    es: '✈️ Vuelo de largo alcance',
    fr: '✈️ Vol long-courrier',
    de: '✈️ Langstreckenflug',
    pt: '✈️ Voo de longa distância',
    ar: '✈️ رحلة طويلة',
    ja: '✈️ 長距離フライト',
    zh: '✈️ 长途飞行',
  },
  'choice.flight.desc': {
    en: 'Highest per-trip carbon footprint',
    hi: 'प्रति यात्रा सबसे अधिक कार्बन',
    es: 'Mayor huella por viaje',
    fr: 'Plus haute empreinte par voyage',
    de: 'Höchster CO₂-Fußabdruck',
    pt: 'Maior pegada por viagem',
    ar: 'أعلى بصمة كربونية لكل رحلة',
    ja: '1回の旅行で最大の炭素フットプリント',
    zh: '每次旅行最高碳足迹',
  },

  // ── Choices — Waste ───────────────────────────────────────────
  'choice.compost': {
    en: '🌱 Compost',
    hi: '🌱 कम्पोस्ट',
    es: '🌱 Compostar',
    fr: '🌱 Composter',
    de: '🌱 Kompostieren',
    pt: '🌱 Compostar',
    ar: '🌱 سماد عضوي',
    ja: '🌱 コンポスト',
    zh: '🌱 堆肥',
  },
  'choice.compost.desc': {
    en: 'Turn organic waste into garden gold',
    hi: 'जैविक कचरे को खाद बनाएं',
    es: 'Convierte residuos en abono',
    fr: 'Transformez déchets en compost',
    de: 'Organischen Abfall kompostieren',
    pt: 'Transforme resíduos em adubo',
    ar: 'حوّل النفايات العضوية إلى سماد',
    ja: '生ごみを堆肥に変換',
    zh: '将有机废物变成花园黄金',
  },
  'choice.recycle': {
    en: '♻️ Recycle',
    hi: '♻️ पुनर्चक्रण',
    es: '♻️ Reciclar',
    fr: '♻️ Recycler',
    de: '♻️ Recyceln',
    pt: '♻️ Reciclar',
    ar: '♻️ إعادة التدوير',
    ja: '♻️ リサイクル',
    zh: '♻️ 回收',
  },
  'choice.recycle.desc': {
    en: 'Proper sorting saves materials & energy',
    hi: 'सही छँटाई सामग्री और ऊर्जा बचाती है',
    es: 'Clasificación correcta ahorra recursos',
    fr: 'Tri correct économise ressources',
    de: 'Richtiges Sortieren spart Ressourcen',
    pt: 'Triagem correta economiza recursos',
    ar: 'الفرز الصحيح يوفر الموارد',
    ja: '適切な分別で材料とエネルギー節約',
    zh: '正确分类节省材料和能源',
  },
  'choice.landfill': {
    en: '🗑️ Landfill',
    hi: '🗑️ लैंडफिल',
    es: '🗑️ Vertedero',
    fr: '🗑️ Décharge',
    de: '🗑️ Mülldeponie',
    pt: '🗑️ Aterro',
    ar: '🗑️ مكب النفايات',
    ja: '🗑️ 埋立地',
    zh: '🗑️ 垃圾填埋场',
  },
  'choice.landfill.desc': {
    en: 'Methane emissions, wasted resources',
    hi: 'मीथेन उत्सर्जन, बर्बाद संसाधन',
    es: 'Emisiones de metano',
    fr: 'Émissions de méthane',
    de: 'Methanemissionen, verschwendete Ressourcen',
    pt: 'Emissões de metano',
    ar: 'انبعاثات الميثان',
    ja: 'メタン排出、無駄な資源',
    zh: '甲烷排放，浪费资源',
  },

  // ── Choices — Digital ─────────────────────────────────────────
  'choice.stream_sd': {
    en: '📱 SD Streaming',
    hi: '📱 SD स्ट्रीमिंग',
    es: '📱 Streaming SD',
    fr: '📱 Streaming SD',
    de: '📱 SD-Streaming',
    pt: '📱 Streaming SD',
    ar: '📱 بث SD',
    ja: '📱 SD配信',
    zh: '📱 标清流媒体',
  },
  'choice.stream_sd.desc': {
    en: 'Lower resolution = less server energy',
    hi: 'कम रेजोल्यूशन = कम सर्वर ऊर्जा',
    es: 'Menor resolución = menos energía',
    fr: 'Moins de résolution = moins énergie',
    de: 'Niedrigere Auflösung = weniger Energie',
    pt: 'Menor resolução = menos energia',
    ar: 'دقة أقل = طاقة أقل',
    ja: '低解像度=サーバーエネルギー削減',
    zh: '低分辨率=更少服务器能耗',
  },
  'choice.dark_mode': {
    en: '🖥️ Dark Mode + Green Host',
    hi: '🖥️ डार्क मोड + ग्रीन होस्ट',
    es: '🖥️ Modo oscuro + Eco host',
    fr: '🖥️ Mode sombre + hébergement vert',
    de: '🖥️ Dark Mode + Grünes Hosting',
    pt: '🖥️ Modo escuro + hospedagem verde',
    ar: '🖥️ الوضع الداكن + استضافة خضراء',
    ja: '🖥️ ダークモード + グリーンホスト',
    zh: '🖥️ 深色模式+绿色主机',
  },
  'choice.dark_mode.desc': {
    en: 'OLED screens use 60% less power in dark mode',
    hi: 'OLED स्क्रीन डार्क मोड में 60% कम बिजली',
    es: 'Pantallas OLED usan 60% menos energía',
    fr: "OLED utilisent 60% moins d'énergie",
    de: 'OLED nutzen 60% weniger Strom im Dark Mode',
    pt: 'OLED usam 60% menos energia',
    ar: 'شاشات OLED تستهلك 60% أقل في الوضع الداكن',
    ja: 'OLEDはダークモードで60%省電力',
    zh: 'OLED屏幕深色模式省电60%',
  },
  'choice.stream_4k': {
    en: '📺 4K Streaming',
    hi: '📺 4K स्ट्रीमिंग',
    es: '📺 Streaming 4K',
    fr: '📺 Streaming 4K',
    de: '📺 4K-Streaming',
    pt: '📺 Streaming 4K',
    ar: '📺 بث 4K',
    ja: '📺 4K配信',
    zh: '📺 4K流媒体',
  },
  'choice.stream_4k.desc': {
    en: '4K streaming uses 7x more data & energy',
    hi: '4K स्ट्रीमिंग 7x अधिक डेटा और ऊर्जा',
    es: '4K usa 7 veces más datos',
    fr: '4K utilise 7x plus de données',
    de: '4K streaming nutzt 7x mehr Daten',
    pt: '4K usa 7x mais dados',
    ar: 'بث 4K يستهلك 7 أضعاف البيانات',
    ja: '4K配信は7倍のデータとエネルギー',
    zh: '4K流媒体消耗7倍数据和能量',
  },

  // ── Results ───────────────────────────────────────────────────
  'results.title': {
    en: 'Your Impact Report',
    hi: 'आपका प्रभाव रिपोर्ट',
    es: 'Tu reporte de impacto',
    fr: "Votre rapport d'impact",
    de: 'Ihr Wirkungsbericht',
    pt: 'Seu relatório de impacto',
    ar: 'تقرير تأثيرك',
    ja: 'あなたの影響レポート',
    zh: '您的影响报告',
  },
  'results.carbon': {
    en: 'Carbon Saved',
    hi: 'कार्बन बचत',
    es: 'Carbono ahorrado',
    fr: 'Carbone économisé',
    de: 'CO₂ eingespart',
    pt: 'Carbono poupado',
    ar: 'الكربون الموفر',
    ja: 'CO₂削減量',
    zh: '节省碳量',
  },
  'results.play_again': {
    en: 'Play Again',
    hi: 'फिर खेलें',
    es: 'Jugar de nuevo',
    fr: 'Rejouer',
    de: 'Nochmal spielen',
    pt: 'Jogar de novo',
    ar: 'العب مرة أخرى',
    ja: 'もう一度プレイ',
    zh: '再玩一次',
  },
  'results.share': {
    en: 'Share',
    hi: 'शेयर करें',
    es: 'Compartir',
    fr: 'Partager',
    de: 'Teilen',
    pt: 'Compartilhar',
    ar: 'مشاركة',
    ja: 'シェア',
    zh: '分享',
  },
  'results.ai_analysis': {
    en: 'AI Analysis',
    hi: 'AI विश्लेषण',
    es: 'Análisis IA',
    fr: 'Analyse IA',
    de: 'KI-Analyse',
    pt: 'Análise de IA',
    ar: 'تحليل الذكاء الاصطناعي',
    ja: 'AI分析',
    zh: 'AI分析',
  },

  // ── Leaderboard ───────────────────────────────────────────────
  'lb.title': {
    en: 'Global Leaderboard',
    hi: 'वैश्विक लीडरबोर्ड',
    es: 'Clasificación global',
    fr: 'Classement mondial',
    de: 'Weltrangliste',
    pt: 'Placar global',
    ar: 'لوحة المتصدرين العالمية',
    ja: 'グローバルランキング',
    zh: '全球排行榜',
  },
  'lb.rank': {
    en: 'Rank',
    hi: 'रैंक',
    es: 'Rango',
    fr: 'Rang',
    de: 'Rang',
    pt: 'Posição',
    ar: 'الترتيب',
    ja: '順位',
    zh: '排名',
  },
  'lb.player': {
    en: 'Player',
    hi: 'खिलाड़ी',
    es: 'Jugador',
    fr: 'Joueur',
    de: 'Spieler',
    pt: 'Jogador',
    ar: 'اللاعب',
    ja: 'プレイヤー',
    zh: '玩家',
  },
  'lb.points': {
    en: 'Points',
    hi: 'पॉइंट',
    es: 'Puntos',
    fr: 'Points',
    de: 'Punkte',
    pt: 'Pontos',
    ar: 'النقاط',
    ja: 'ポイント',
    zh: '分数',
  },
  'lb.carbon': {
    en: 'CO₂ Saved',
    hi: 'CO₂ बचत',
    es: 'CO₂ ahorrado',
    fr: 'CO₂ économisé',
    de: 'CO₂ gespart',
    pt: 'CO₂ poupado',
    ar: 'CO₂ موفر',
    ja: 'CO₂削減',
    zh: '节省CO₂',
  },

  // ── Common ────────────────────────────────────────────────────
  'common.loading': {
    en: 'Loading…',
    hi: 'लोड हो रहा है…',
    es: 'Cargando…',
    fr: 'Chargement…',
    de: 'Lädt…',
    pt: 'Carregando…',
    ar: 'جارٍ التحميل…',
    ja: '読み込み中…',
    zh: '加载中…',
  },
  'common.error': {
    en: 'Something went wrong. Please try again.',
    hi: 'कुछ गलत हो गया।',
    es: 'Algo salió mal.',
    fr: 'Quelque chose a mal tourné.',
    de: 'Etwas ist schief gelaufen.',
    pt: 'Algo deu errado.',
    ar: 'حدث خطأ ما.',
    ja: 'エラーが発生しました。',
    zh: '出了问题。',
  },
  'common.close': {
    en: 'Close',
    hi: 'बंद करें',
    es: 'Cerrar',
    fr: 'Fermer',
    de: 'Schließen',
    pt: 'Fechar',
    ar: 'إغلاق',
    ja: '閉じる',
    zh: '关闭',
  },
  'common.back': {
    en: 'Back',
    hi: 'वापस',
    es: 'Volver',
    fr: 'Retour',
    de: 'Zurück',
    pt: 'Voltar',
    ar: 'رجوع',
    ja: '戻る',
    zh: '返回',
  },
  'common.skip': {
    en: 'Skip',
    hi: 'छोड़ें',
    es: 'Saltar',
    fr: 'Passer',
    de: 'Überspringen',
    pt: 'Pular',
    ar: 'تخطي',
    ja: 'スキップ',
    zh: '跳过',
  },
};

// ── Context types ──────────────────────────────────────────────────────────
interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

// ── Provider ───────────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
    return stored ?? DEFAULT_LANGUAGE;
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    document.documentElement.lang = lang;
    // RTL support for Arabic
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = useCallback(
    (key: TranslationKey, fallback?: string): string => {
      const entry = translations[key];
      if (!entry) {
        if (import.meta.env.DEV) console.warn(`[i18n] Missing key: "${key}"`);
        return fallback ?? key;
      }
      return entry[language] ?? entry['en'] ?? fallback ?? key;
    },
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ── Hook ───────────────────────────────────────────────────────────────────
export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within <LanguageProvider>');
  return ctx;
}
